//const endPoint = 'http://localhost:3100/'
const endPoint = 'https://buybuddyrestapi.azurewebsites.net:80/'

exports.endPointUReg = endPoint+'uerReg/';
exports.endPointULogin = endPoint+'uLogin/';
exports.endPointAddCategories = endPoint+'addCategories/';
exports.endPointCategories = endPoint+'categories/';
exports.endPointAddProduct = endPoint+'addProduct/';
exports.endPointViewProduct = endPoint+'products/';
exports.endPointHomePageProducts = endPoint+'getProducts/';
exports.endPointAddToCart = endPoint+'addToCart/';
exports.endPointOrders = endPoint+'vieworders/';
exports.endPointRemoveCart = endPoint+'removeCart/';
exports.endPointOrderNow = endPoint+'orderNow/';
exports.endPointDispatch = endPoint+'dispatchOrder/';
exports.endPointMakeAsRecieved = endPoint+'makeasRecieved/';
exports.endPointGiveRating = endPoint+'giveRating/';
exports.endPointProfile = endPoint+'userProfile/';
exports.endPointGetProductDetails = endPoint+'getProductDetails/';
exports.endPointSimilarProducts = endPoint+'getSimilarProducts/';
exports.endPointGetCartCount = endPoint+'getCartCount/';
exports.endPointProductStatusAction = endPoint+'productStatusAction/';
exports.endPointOrderHistory = endPoint+'ordersHistory/';
exports.endPointAddWishList = endPoint+'addToWishList/';
exports.endPointViewWishList = endPoint+'viewWishList/';
exports.endPointWishListCount = endPoint+'WishListCount';